name: Deploy main branch on staging

on:
  push:
    branches:
      - main
      - ci/auto-deploy

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - run: npm ci
      - uses: serverless/github-action@v3
        with:
          args: deploy --stage=staging
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - uses: actions/upload-artifact@v3
        with:
          name: serverless-compose-log
          path: .serverless/compose.log
