name: Deploy main branch on staging

on:
  push:
    branches:
      - main
      - ci/auto-deploy

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - run: npx serverless deploy --stage=staging --verbose
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
