name: Deploy main branch on staging

on:
  push:
    branches:
      - main
      - ci/auto-deploy

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy --stage=staging
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
